package com.mfood.bot.domain.enums;

public enum UserState {
    IDLE,
    AWAITING_LANGUAGE,
    AWAITING_PHONE,
    AWAITING_AGE,
    AWAITING_HEIGHT,
    AWAITING_WEIGHT,
    AWAITING_SEX,
    AWAITING_ACTIVITY,
    AWAITING_GOAL,
    MAIN_MENU,
    AWAITING_MEAL_PHOTO,
    AWAITING_MEAL_TEXT,
    AWAITING_REMINDER_TIME,
    AWAITING_MEAL_CONFIRM
}
